services:
  alloy:
    image: grafana/alloy:v1.11.3
    container_name: alloy
    restart: unless-stopped
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy:ro
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy
    environment:
      - ALLOY_LOG_LEVEL=info
    depends_on:
      - tempo
      - loki
    networks:
      - dokploy-network

  tempo:
    image: grafana/tempo:2.9.0
    container_name: tempo
    restart: unless-stopped
    volumes:
      - ./tempo.yaml:/etc/tempo/tempo.yaml:ro
    command:
      - -config.file=/etc/tempo/tempo.yaml
    networks:
      - dokploy-network

  loki:
    image: grafana/loki:3.5.8
    container_name: loki
    restart: unless-stopped
    volumes:
      - ./loki.yaml:/etc/loki/loki.yaml:ro
    command:
      - -config.file=/etc/loki/loki.yaml
    networks:
      - dokploy-network

  grafana:
    image: grafana/grafana:12.2.1
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./provisioning:/etc/grafana/provisioning:ro
      # - ./dashboards:/var/lib/grafana/dashboards:ro
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph traceqlSearch traceQLStreaming correlations metricsSummary traceqlEditor traceToMetrics traceToProfiles
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_PLUGINS_ENABLE_ALPHA=false
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES=false
    depends_on:
      - tempo
      - loki
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
